/**
 * Spanish drafts for technique names and "when" fields, which the spec gives only in English (sections 8.2-8.10).
 * Written for Miami usage in the usted register; every technique file keeps `spanish_reviewed: false` until a
 * native Miami speaker approves it (spec 16.3).
 */
export const NAME_ES: Record<string, string> = {
  T001: "Hacer una pausa y bajar el ritmo",
  T002: "Aclarar con una pregunta",
  T003: "Reconocer",
  T004: "Ponerle nombre a la preocupación",
  T005: "Aislar la objeción",
  T006: "Preguntas de descubrimiento",
  T007: "Resumir y confirmar",
  T008: "Conectar la característica con la necesidad que dijo",
  T009: "Números transparentes",
  T010: "Cierre de prueba",
  T011: "Escoger entre dos",
  T012: "Historia real de otro cliente",
  T013: "Incluir a quien decide y no está",
  T014: "Un siguiente paso concreto",
  T015: "Anclar con el precio real y una razón",
  T016: "Silencio después del número",
  T017: "Vender el valor antes de rebajar",
  T018: "Intercambiar, nunca regalar",
  T019: "Concesiones pequeñas y cada vez menores",
  T020: "Urgencia real",
  T021: "Takeaway (quitar la opción)",
  T022: "Achicar la diferencia",
  T023: "Un solo cierre en el momento justo",
  T024: "Preguntas de implicación",
  T025: "Preguntas de necesidad-beneficio",
  T026: "Cierre de resumen",
  T027: "Número exacto con una razón",
  T028: "Contrarrestar un ancla baja cambiando el enfoque",
  T029: "Explicar el valor del trade-in paso a paso",
  T030: "Primero el precio total final",
  T031: "\"Usted está en libertad de decir que no\"",
  T032: "Repetir las últimas palabras",
  T033: "Las manos en el carro desde temprano",
  T034: "Llevárselo a casa de prueba",
  T035: "Pintarle la imagen por teléfono",
  T036: "Devolver la llamada en cinco minutos",
  T037: "Presentar al gerente temprano",
  T038: "Enseñarle algo nuevo",
  T039: "Seguimiento programado de funciones",
  T040: "Preguntar el idioma preferido",
  T041: "El mismo negocio en los dos idiomas",
  T042: "Escalera de concesiones a la vista",
  T043: "Negociar todo en paquete",
  T044: "Compromiso condicional",
  T045: "Adelantarse a la objeción conocida",
  T046: "Opción más barata antes de la prueba de manejo",
  T047: "Pros y contras en papel",
  T048: "Amarre, usado con moderación",
  T049: "Preparar la visita a financiamiento",
  T050: "Pasar lo que aprendió",
  T051: "No prejuzgar los productos",
  T052: "Ley de los 250",
  T053: "Pedir referidos en la entrega",
  T054: "Contacto mensual",
  T055: "Ficha del cliente",
  T056: "Redirigir hacia el valor",
  T057: "Primero estar de acuerdo",
  T058: "Medir qué tan seguro está",
  T059: "Sí o no, no un tal vez",
  T060: "Quién más decide, preguntado temprano",
  T061: "Tres opciones y luego silencio",
  T062: "Dar el número y luego una razón para venir",
  T063: "Dos horarios de cita con una razón",
  T064: "Video y confirmación con nombre",
  T065: "Replantear con las millas diarias",
  T066: "Hoja de costo total de propiedad",
  T067: "Llamada de revisión anual",
  T068: "Avanzar, no \"me avisa\"",
  T069: "Pedir permiso antes de contestar",
  T070: "Explicar cómo se compra aquí",
  T071: "Presentar a servicio en la entrega",
  T072: "Mostrar el reporte de la batería",
  T073: "Hablar claro sobre el calor",
  T074: "La tranquilidad de los 60 días",
  T075: "Apertura telefónica de diez segundos",
  T076: "Confirmación en dos contactos",
  T077: "Cambiar de canal si no contesta",
  T078: "Llamada al cliente huérfano",
  T079: "Oferta por el trade-in por separado",
  T080: "Lo que significa el carro",
  T081: "Llamada de seguimiento de funciones",
  T082: "Primero el trade-in",
  T083: "Recorrer la rueda",
  T084: "Saludo de \"apenas empezando a mirar\"",
  T085: "Transparencia anunciada",
  T086: "Lado a lado para \"aquí cerca me lo dejan más barato\"",
  T087: "Ganarse los referidos sin pedirlos",
  T088: "Disculpa por la cita perdida",
  T089: "Nosotros contra el problema",
  T090: "Repasar la historia, la solución al final",
  T091: "Ponerle nombre al miedo",
  T092: "Recomendación personal",
  T093: "Limitar la búsqueda",
  T094: "Quitar el riesgo real",
  T095: "Paquetes equivalentes",
  T096: "El trade-in en su propia línea cuando es fuerte",
  T097: "Por día solo para extras pequeños",
  T098: "Una opción del medio honesta",
  T099: "La pregunta del \"cómo\"",
  T100: "Decir primero sus dudas",
  T101: "Pregunta donde el \"no\" significa sí",
  T102: "Llamada con la razón primero",
  T103: "Adaptarse al estilo del comprador",
  T104: "Algo real en común",
  T105: "Voz firme al dar el precio",
  T106: "Escalera de concesiones",
  T107: "Fecha límite real sobre la mesa",
  T108: "Disculparse por lo que usted no causó",
  T109: "\"¿Qué hubiera hecho falta?\"",
  T110: "Ver una exigencia firme como una pista",
  T111: "Poner la condición por escrito",
  T112: "Preguntar qué le parece justo",
  T113: "Los sentimientos antes que los números",
  T114: "Ofrecer lo que cuesta poco dar",
  T115: "Fijar la hora y luego preguntar qué quiere pensar",
  T116: "Pedir la reseña más adelante",
  T117: "Cuidar el final",
  T118: "Precio con todo incluido por teléfono o texto",
  T119: "Primero el precio que cualquiera puede pagar",
  T120: "Opcional quiere decir opcional",
  T121: "Menú de dos pagos",
  T122: "Un \"ahora no\" con buena cara",
};

export const WHEN_ES: Record<string, string> = {
  T001: "En el instante en que llega cualquier objeción",
  T002: "Antes de contestar cualquier objeción",
  T003: "Justo después de la pausa",
  T004: "La emoción va por delante de la lógica",
  T005: "Puede que la objeción que dice no sea la verdadera",
  T006: "En el descubrimiento, y siempre que esté adivinando",
  T007: "Al final del descubrimiento, antes de los números",
  T008: "En el recorrido alrededor del carro",
  T009: "Al presentar las cifras",
  T010: "Después de la prueba de manejo y de cada objeción resuelta",
  T011: "Cerca de decidirse, pero atascado",
  T012: "Miedo a equivocarse",
  T013: "La pareja, el papá o la mamá no está presente",
  T014: "Cualquier cliente que se está yendo",
  T015: "El primer número",
  T016: "Justo después de presentar las cifras",
  T017: "La primera objeción al precio",
  T018: "Cualquier pedido de una concesión",
  T019: "Varias rondas",
  T020: "Una fecha límite verdadera que se puede mostrar, o una unidad escasa",
  T021: "Quiere la versión más alta al precio de la básica",
  T022: "Queda una diferencia pequeña",
  T023: "Después de confirmar las necesidades",
  T024: "En el descubrimiento",
  T025: "Al final del descubrimiento",
  T026: "La forma normal de pedir la venta",
  T027: "La primera propuesta de números, la oferta por el trade-in",
  T028: "\"Otro dealer está más barato\"",
  T029: "\"Me está dando poco por mi trade-in\"",
  T030: "En cada conversación de precio",
  T031: "Al pedir la prueba de manejo, en el cierre, en el takeaway",
  T032: "Cuando el cliente se frena",
  T033: "Desde el saludo hasta la prueba de manejo",
  T034: "Cerca de decidirse, pero con dudas",
  T035: "Leads de teléfono e internet",
  T036: "Cada lead de internet",
  T037: "Después de la prueba de manejo, antes de los números",
  T038: "Compradores que investigaron bien",
  T039: "Dos o tres semanas después de la entrega",
  T040: "En los primeros dos minutos, y antes del financiamiento",
  T041: "Un comprador que habla español y desconfía",
  T042: "\"¿Ese es su último precio?\"",
  T043: "El comprador sigue reabriendo puntos sueltos",
  T044: "El comprador menciona un solo obstáculo",
  T045: "Un cargo o una espera con la que se va a topar de todos modos",
  T046: "Comprador que cuida el presupuesto",
  T047: "Comprador analítico atascado entre dos",
  T048: "Después de un beneficio que el comprador claramente valora",
  T049: "El cliente acepta los números",
  T050: "Antes de financiamiento",
  T051: "\"¿Necesito la garantía?\"",
  T052: "Cada cliente, sobre todo el que se va sin comprar",
  T053: "En la entrega y en los seguimientos",
  T054: "Cada cliente que compró",
  T055: "Después de cada venta y de cada cliente que se va sin comprar",
  T056: "Pregunta el precio antes de escoger un carro",
  T057: "Las primeras palabras de cualquier respuesta a una objeción",
  T058: "Después de la prueba de manejo, antes de los números",
  T059: "Al empezar a escribir la propuesta",
  T060: "En el saludo o el descubrimiento",
  T061: "Los primeros números",
  T062: "\"Nada más mándeme el precio por email\"",
  T063: "Cualquier lead de teléfono o internet",
  T064: "Después del primer contacto y el día antes",
  T065: "Preocupación por la autonomía del eléctrico",
  T066: "\"Los eléctricos cuestan más\"",
  T067: "Clientes que compraron, una vez al año",
  T068: "Al final de cada etapa",
  T069: "Objeciones de precio o de confianza",
  T070: "Al principio, con quienes compran por primera vez",
  T071: "En la entrega",
  T072: "Eléctrico usado, preocupación por la batería",
  T073: "Compradores de eléctricos en Miami",
  T074: "Duda sobre un contrato de servicio",
  T075: "Cada llamada de ventas",
  T076: "El día antes y la mañana de la cita",
  T077: "Después de uno o dos contactos sin respuesta",
  T078: "Dueños cuyo vendedor se fue; compradores de hace unos dos años",
  T079: "El cliente sospecha que le están moviendo el valor del trade-in",
  T080: "En el descubrimiento, con quien compra su primer carro o compra para la familia",
  T081: "Tres semanas después de la entrega (versión telefónica de T039)",
  T082: "Justo después del saludo, cuando hay trade-in",
  T083: "Cliente fijado en el precio, ya en la mesa",
  T084: "Saludo en el lote",
  T085: "En el lote, y otra vez con los primeros números",
  T086: "El cliente menciona una cotización más baja",
  T087: "Construir la cartera de clientes a largo plazo",
  T088: "Después de que el cliente no llegó a la cita, solo si es cierto",
  T089: "Tensión en la mesa",
  T090: "Antes de la demostración",
  T091: "Se frena sin una objeción clara",
  T092: "Está indeciso, o pregunta qué haría usted",
  T093: "Quiere hacer una comparación más",
  T094: "Miedo a que le salga malo el carro o a escoger mal",
  T095: "Los primeros números, después del descubrimiento",
  T096: "Al presentar el trade-in",
  T097: "Un producto opcional con precio aparte",
  T098: "Al escoger versión o paquete",
  T099: "El cliente exige un número al que usted no puede llegar",
  T100: "Comprador desconfiado o que ya se quemó antes",
  T101: "Al pedir la prueba de manejo o el siguiente paso",
  T102: "Leads viejos y clientes anteriores",
  T103: "El enfoque actual no avanza",
  T104: "En el saludo y el recorrido alrededor del carro, solo si es cierto",
  T105: "Al decir cualquier número",
  T106: "Negociación en la mesa",
  T107: "Solo cuando existe una fecha límite que se puede mostrar",
  T108: "En el saludo y al devolver llamadas",
  T109: "Después de un no firme o un negocio perdido",
  T110: "\"Necesito $400 al mes, y punto\"",
  T111: "El valor del trade-in depende de un payoff sin confirmar",
  T112: "Estancados en el precio",
  T113: "Cliente que regresa molesto",
  T114: "Al cerrar la última diferencia",
  T115: "\"Lo voy a pensar\"",
  T116: "Unos diez días después de la entrega",
  T117: "En la entrega",
  T118: "Cualquier precio que se da fuera de la mesa",
  T119: "Un reembolso para el que solo califican algunos compradores",
  T120: "El cliente objeta un paquete que ya viene instalado",
  T121: "Al presentar cualquier extra",
  T122: "El cliente se va sin decidirse",
};
