/**
 * Spanish drafts for fields the spec gives only in English (objection "behind it" and free-text core moves).
 * Written for Miami usage in the usted register by the build, so every file they land in keeps
 * `spanish_reviewed: false` until a native Miami speaker approves it (spec 16.3).
 */

export const BEHIND_ES: Record<string, string> = {
  O01: "Una decisión de verdad en pareja, o una salida amable que esconde una preocupación por el pago",
  O02: "Miedo de que los números no den; vergüenza. El 29.6% de los trade-ins de carros nuevos estaban al revés en el segundo trimestre de 2026, por $6,884 en promedio (Edmunds)",
  O03: "Un número de presupuesto que todavía no ha dicho",
  O04: "Una comparación que usted todavía no ha visto",
  O05: "Una pregunta que no se ha dicho; miedo de escoger mal",
  O06: "Está a la defensiva; miedo a la presión",
  O07: "Quiere controlar sus propios tiempos",
  O08: "Un estimado de internet o cariño por su carro; al 28% le dieron menos de lo que esperaba (J.D. Power)",
  O09: "No está convencido del precio o de la tienda",
  O10: "Una cotización que quizás no es comparable",
  O11: "Desconfianza del financiamiento del dealer",
  O12: "Vergüenza; miedo a que lo rechacen delante de otros",
  O13: "Está corto de efectivo, o está probando",
  O14: "Está comparando sin venir a la tienda",
  O15: "No está convencido del carro, o anda apurado",
  O16: "Una preferencia real, o una salida fácil",
  O17: "Miedo de pagar de más",
  O18: "Una mala experiencia en el pasado",
  O19: "Se siente engañado con el anuncio",
  O20: "Miedo de que le metan cosas en el pago",
  O21: "Ya tiene su propio financiamiento",
  O22: "Sospecha de que lo están cambiando por otro carro",
  O23: "Quiere un trato justo más que una cifra más alta",
  O24: "Urgencia real, con riesgo de arrepentirse después",
  O25: "Le preocupa el gasto de gasolina; la escasez es real",
  O26: "El primero que le contestó le marcó la pauta",
  O27: "Se sintió abrumado en la entrega",
  O28: "Miedo de quedarse varado",
  O29: "Se imagina esperando en un cargador público",
  O30: "Una barrera real (el 34% de los que rechazan los eléctricos, YouGov 2026)",
  O31: "Miedo a una reparación carísima",
  O32: "Solo está comparando el precio de etiqueta",
  O33: "Un negocio donde no se ve ninguna rebaja se siente injusto",
  O34: "Miedo a condiciones escondidas",
  O35: "Miedo a que lo rechacen",
  O36: "Historial de crédito muy corto",
  O37: "Las condiciones no se dijeron en español",
  O38: "La barrera del idioma esconde confusión",
  O39: "Se siente estereotipado",
  O40: "Espera regatear; no conoce los cargos de Estados Unidos",
  O41: "Miedo a que le cambien el precio cuando llegue",
  O42: "Una cotización a la que le faltan cargos o el trade-in",
  O43: "Miedo a perder valor",
  O44: "Es verdad; quiere saber qué lo reemplaza",
  O45: "Miedo a la reventa; los eléctricos pierden el 57.2% en cinco años contra el 41.8% de todos los vehículos (iSeeCars 2026)",
  O46: "Una mala experiencia en el pasado",
  O47: "Cree que tiene un derecho de cancelación que no aplica",
  O48: "Le preocupa el clima",
  O49: "Le dieron información equivocada antes",
  O50: "Desconfianza después de cargos escondidos",
  O51: "Miedo de que la diferencia se esconda en el préstamo nuevo",
  O52: "Crédito corto, miedo a que lo rechacen",
  O53: "Una mala experiencia en el pasado",
  O54: "Sabe que a veces meten productos en el pago",
  O55: "Una cotización a la que le faltan cargos, o una prueba",
  O56: "Vergüenza, u otra tienda",
  O57: "Una cifra de una máquina que puede estar equivocada",
  O58: "Quiere que alguien se haga responsable del consejo",
  O59: "Está atascado comparando",
  O60: "No hacer nada se siente más seguro",
  O61: "Esperar se siente seguro",
  O62: "Le cuesta escoger; no es el precio",
  O63: "Muchas veces es un farol",
  O64: "Una rebaja rápida y sin explicación",
  O65: "Se siente obligado a pagar extras",
};

/** Free-text core moves (the part of the "Core moves" column that is not a technique or rule code). */
export const MOVES: Record<string, { en: string; es: string }> = {
  O02: { en: "Honest options, including waiting", es: "Opciones honestas, incluyendo esperar" },
  O11: { en: "Welcome outside financing", es: "Bienvenido su financiamiento de afuera" },
  O12: { en: "Explain privately", es: "Explicarle en privado" },
  O13: { en: "Show both paths with real numbers", es: "Mostrar los dos caminos con números reales" },
  O15: { en: "Offer a short route", es: "Ofrecer una ruta corta" },
  O16: { en: "Locate or order the vehicle", es: "Localizar o pedir el vehículo" },
  O17: { en: "Share what is known; never predict the market", es: "Compartir lo que se sabe; nunca predecir el mercado" },
  O19: { en: "Apologize and show the full breakdown", es: "Disculparse y mostrar el desglose completo" },
  O20: { en: "Remove it and offer it as a priced option", es: "Quitarlo y ofrecerlo como opción con su precio" },
  O21: { en: "A price that stands with any financing", es: "Un precio que se mantiene con cualquier financiamiento" },
  O22: { en: "Show when it sold; offer the nearest real match", es: "Mostrar cuándo se vendió; ofrecer el más parecido que sí hay" },
  O24: { en: "Confirm the facts; keep within budget", es: "Confirmar los datos; mantenerse en el presupuesto" },
  O25: { en: "Real supply data; inbound units", es: "Datos reales de inventario; unidades en camino" },
  O26: { en: "Ask what they were quoted; compare out-the-door", es: "Preguntar qué le cotizaron; comparar el precio total final" },
  O29: { en: "Ask where the car sleeps at night", es: "Preguntar dónde duerme el carro de noche" },
  O30: { en: "Be straight; show a hybrid", es: "Hablarle claro; mostrarle un híbrido" },
  O31: { en: "Warranty in writing", es: "La garantía por escrito" },
  O32: { en: "Verified figures only", es: "Solo cifras verificadas" },
  O34: { en: "Store policy set with counsel", es: "Política de la tienda definida con el abogado" },
  O35: { en: "Explain options privately; never claim only one lender approves", es: "Explicar las opciones en privado; nunca decir que un solo banco aprueba" },
  O36: { en: "Real paths, such as a co-signer", es: "Caminos reales, como un co-firmante" },
  O37: { en: "Explain every condition in Spanish", es: "Explicar cada condición en español" },
  O38: { en: "Offer a bilingual staff member", es: "Ofrecer a alguien del equipo que sea bilingüe" },
  O43: { en: "Be straight; show a lease or a used EV", es: "Hablarle claro; mostrarle un lease o un eléctrico usado" },
  O44: { en: "Confirm it; current incentives in writing", es: "Confirmarlo; los incentivos actuales por escrito" },
  O45: { en: "Honest data; a hybrid or a lease", es: "Datos honestos; un híbrido o un lease" },
  O46: { en: "\"Nothing is added without your yes\"", es: "\"No se agrega nada sin que usted diga que sí\"" },
  O47: { en: "Correct it honestly; slow down", es: "Corregirlo con honestidad; ir más despacio" },
  O48: { en: "Warranty", es: "La garantía" },
  O49: { en: "\"GAP is optional\"", es: "\"El GAP es opcional\"" },
  O50: { en: "Show it on the invoice", es: "Enseñárselo en la factura" },
  O51: { en: "Payoff and value side by side", es: "El payoff y el valor lado a lado" },
  O52: { en: "Explain the process; never promise approval", es: "Explicar el proceso; nunca prometer la aprobación" },
  O53: { en: "Plain words; every number in writing", es: "Palabras sencillas; cada número por escrito" },
  O57: { en: "See it, then compare line by line", es: "Verla y comparar línea por línea" },
  O61: { en: "Facts on what waiting costs", es: "Datos de lo que cuesta esperar" },
  O63: { en: "Ask about their current car's situation", es: "Preguntar cómo está su carro actual" },
};

/** Customer lines the spec gives only as a cross-reference or description. */
export const SAYS_OVERRIDES: Record<string, { en: string; es: string; nonverbal?: boolean; languageSpecific?: { language: "en" | "es"; reason: string }; seeAlso?: string[] }> = {
  O39: { en: "(Addressed in Spanish without being asked; answers in English)", es: "(Le hablan en español sin preguntarle; contesta en inglés)", nonverbal: true },
  O51: { en: "", es: "Estoy al revés con mi carro", languageSpecific: { language: "es", reason: "Spanish phrasing of O02 used by Miami customers" }, seeAlso: ["O02"] },
  O55: { en: "I have got you beat down the road", es: "Aquí cerca me lo dejan más barato", seeAlso: ["O10"] },
  O56: { en: "(The no-show who goes quiet)", es: "(El cliente que no llega a la cita y deja de contestar)", nonverbal: true },
  O62: { en: "(Goes silent after two options)", es: "(Se queda callado después de ver dos opciones)", nonverbal: true },
};

/** Trailing "use only when" notes in model lines, and the Spanish for the one the spec gives only in English. */
export const USE_ONLY_WHEN_ES_FALLBACK: Record<string, string> = {
  T120: "La política de la tienda define la solución.",
};
